Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 3

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 4096
  end
end
