{{- if .Values.backup.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-secret
spec:
  encryptedData:
    aws_access_key_id: {{ .Values.backup.sealedSecret.aws_access_key_id }}
    aws_secret_access_key: {{ .Values.backup.sealedSecret.aws_secret_access_key }}
    restic_password: {{ .Values.backup.sealedSecret.restic_password }}
  template:
    metadata:
      name: backup-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
