apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-deployment
  labels:
    app: astro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro
  template:
    metadata:
      labels:
        app: astro
    spec:
      containers:
      - name: astro
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        volumeMounts:
          - name: astro-data
            mountPath: /usr/share/nginx/html/public
        resources: {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: astro-data
        persistentVolumeClaim:
          claimName: astro-pvc
