image:
  repository: cloudflare/cloudflared
  tag: 2026.3.0

resources:
  limits:
    cpu: "0.5"
    memory: "256Mi"
  requests:
    cpu: "0.05"
    memory: "64Mi"

probes:
  enabled: false

tunnel_id: 97c7ebb0-842d-4ab0-96bb-6a119dd3bec3

ingress:
  - hostname: nopsqi.dev
    service: http://astro-service.astro.svc.cluster.local:80
  - hostname: actual.nopsqi.dev
    service: http://actual-service.actual.svc.cluster.local:5006
  - hostname: minio.nopsqi.dev
    service: http://minio-service.minio.svc.cluster.local:9000
  - hostname: minio-console.nopsqi.dev
    service: http://minio-service.minio.svc.cluster.local:9001
  - hostname: argocd.nopsqi.dev
    service: https://argocd-server.argocd.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
  - hostname: grafana.nopsqi.dev
    service: http://monitoring-grafana.monitoring.svc.cluster.local:80
