image:
  repository: cloudflare/cloudflared
  tag: 2026.3.0

resources:
  limits:
    cpu: "0.5"
    memory: "256Mi"
  requests:
    cpu: "0.05"
    memory: "64Mi"

probes:
  enabled: true

networkPolicy:
  enabled: true

sealedSecret:
  credentials_json: AgCGeLaR+YL0p2S6/UcCdodpVOQFsNwDoFqCbUJITeQEgS4slH5EIVx5HGNGAssXNi+YRUA5/UCGGBVvNWtHIhgikPZuhry98gDQ9hs+wSq0/X8BgphBg7Y/6rEdn5SGbpbHGeRkA5EdwWM8GffTf0Wg1w/cEX4jW9+e0CSajM0xA/fSGDgOHO01Zf6nnGE6Ss7wTdph+kI8GgbuhEvVzRV7TC5A5Ncul0wx+1kAu9/WviXrSjDypy1GzWoBGTnvP+dGxtVF3O4iibGgDQ6+whgkXwaWy+nnseLuhjZMT4DtlRu5MsNKffw9/rrJuRienUOjGPFDXnSNcwyy2ml7Enn4qPK19c525mRTojjJ9jprgwDmY9Fezgq1Sd/pCTpPqZkA5A6MBom1AH4fy0fwa7kVQ2b3fYNQpbJHFWavk9KcnM+iem8c6x3o8nykfNen+e+tf9G2GcvytTiuWTWl8ms3HKH5TO+HEW3brKxjIKdUIQ3NxlZd6yYuFiHAGs03R3elDFpSap0kSVK4mTIcFeq/muQjJfW3YtN78+0KqXgvyeZGKzf4Y9i7cYFqlHfl49pV+7kTXoJ2JlQzhtkn7hJzUyHzowWhJTTww0TtFL4opZyc41Ta0eolWCqAMDV9BtAJBU9viz0b5IJAqgFAdNbobmn1VXOUQBSW9LI8Nbs+3C+MI0FAVtA11li1+yvYjuK69lg6Dfitv/iL356kFPT2zE4g+EtDGcBMyUp2YxpzwFSOqveNMb1dy7F7nn3af2g2/wXwUFxModsneLmv1mdOiGyyBAP8mgGJktj5pvqMSTm2G6lsy07xukV+cJaZdVjRpJI/vZ04c5UboxbBmFUJbEUENwIu+qpeDXsCRqdcBCEhalQu4cddQnl8c+qsgm1sqglN39MhZInfyaadftubJeSOOWRDm/frvhPEe0u2

tunnel_id: 97c7ebb0-842d-4ab0-96bb-6a119dd3bec3

ingress:
  - hostname: nopsqi.dev
    service: http://astro-service.astro.svc.cluster.local:80
  - hostname: actual.nopsqi.dev
    service: http://actual-service.actual.svc.cluster.local:5006
  - hostname: minio.nopsqi.dev
    service: http://minio-service.minio.svc.cluster.local:9000
  - hostname: minio-console.nopsqi.dev
    service: http://minio-service.minio.svc.cluster.local:9001
  - hostname: argocd.nopsqi.dev
    service: https://argocd-server.argocd.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
  - hostname: grafana.nopsqi.dev
    service: http://monitoring-grafana.monitoring.svc.cluster.local:80
