apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: {{ .Values.tunnel_id }}
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      {{- range .Values.ingress }}
      - hostname: {{ .hostname }}
        service: {{ .service }}
      {{- end }}
      - service: http_status:404
