{{- if .Values.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-secret
spec:
  encryptedData:
    credentials.json: {{ .Values.sealedSecret.credentials_json }}
  template:
    metadata:
      name: cloudflared-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
