customAlerts:
  enabled: false

customDashboards:
  enabled: false

networkPolicy:
  enabled: false

kube-prometheus-stack:
  alertmanager:
    enabled: true
    alertmanagerSpec:
      configSecret: alertmanager-discord

  prometheusOperator:
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"

  prometheus:
    prometheusSpec:
      retention: 7d
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

  grafana:
    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password
    ingress:
      enabled: false
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki.svc.cluster.local:3100
        access: proxy

  kubeProxy:
    enabled: false

  kubeControllerManager:
    enabled: false

  kubeScheduler:
    enabled: false

  nodeExporter:
    enabled: true

  kubeStateMetrics:
    enabled: true

  kube-state-metrics:
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
