customAlerts:
  enabled: true

customDashboards:
  enabled: true

networkPolicy:
  enabled: true

kube-prometheus-stack:
  alertmanager:
    enabled: false

  kube-state-metrics:
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10

  prometheus:
    prometheusSpec:
      storageSpec: {}

sealedSecrets:
  grafana:
    admin_user: AgAWo7L4l8k2b73blCr49HnryQwA2KuUwR1uHm2Ls34/3/08/U9opj3pnD6+6aIwIWprVMVcKfWa/VIQ60umnKICPPQjCDdjzn0SgBYdxJDM/hRjY+RKGuD9kMo5SZz7+P5YXuOuxlpqsw8m3yk4M7IPgBbqy3XQ//mWdLzXUoRDLe8BUCWYUhyaSLoRk1DaLpY9lFRn6nRqjsW7gBPUrrzcoVI9limlTJLWo8ur5CJ1IqlLJolru/1lIG7M5i0+9DRsHkuFVV31wdGER02eaOa4H2uBNAg0wWpbchTWxN63gOLcyV/qUi9J5lLgkNcNOie1sWFUurkYLW/Be9I81gV+5pmKSSvlMarCJKRr3yuCh/Fm/20Hd1PHvASlN+H+dAgZwAnQEyZ7J/XH1Dm8h7/E577bO0edXQz9Bcy4CGH5/BLjAQYC7ymfffqr8U8VgG9r4TCRuKQU4xsKHGoL11+UK+WXo4InneFWRHrF98XIu8H0fPaWLYr0V/a4OkLgvCrt9HmN6yYyCiByb7V7fAcdTkGDNnYvuK/xZRJlZxxjpiy5ezMHSFfz7Cg7L0zffIqXEzwCgqTfHhkgA8f2jouMvg+PfisvzNXBR6WbzJ583gamDPhCGy7xNDcjNgEKFDgclqkbxh8AmLDCPx/qRC3nIHJIby6s7puR//Typ5bHwfgQjsFYwhzDNv9xufAraLXUg9xsJA==
    admin_password: AgBj5KGptjeIucjMrYIgqQCfBC0jhb2khhfITMjYn3XIwzmtq8u8WswktrPkrNP3RvsTcAdGjYTEQOilAwJaXM1JKI9Hcc5K14ovKGOod4uCiwlmhgz3LboyVvGDNSl+Qb74O6DvM9lF9VuIaO9ikqXQ36+TN9hGFX8OpGMc4F6lH6GP3tn7wIeVtCXbySbMzuD53EZrvaeuh0ue5tO6wTJ8ihsYQGWMsiP/bPsXg7Vda+/johblTljN4Og8rf1z5Ql8wW9PdIFeKqUSqPzoCSQKxO16+VdQBQnwgeyu1cE05rrM3GREp1FoxC+jyl6XeXTuckrjrf6A2iFMyMCBqnsKnkwwpPQkgrUsgNLArk9cIWlm6EU/TceI0WYcBnulw8yKtjcaUn0/6P94aU++JCXKTZxkDbKWrJP8PUZqDKRWUgKrngTZDK0Be0MNGZRufb0TB/VuSRdttFUX8qbTxh1u3sBv7+7poD0Ek/eOooOs5fl4qDubNqPL5npatmnIyYlwzycn+XEZm3hrZWW8SILXta9hh3I/Ri3V/C7tnlXMBvzmw/6atTpY0dyYqhEtaB2Xo1PE9BkdGXsk+5dcA4C46OZ11lC24++rPEMKSL8TfhnEY0HnEmeqdmqOFYgFeOZ+LeGdSXFqsuzBVl+EiS10lxlj95jQ59JwC3Y4l55jFASpp9FI01IksKxtT7Voe5WqSUkvo+pzafXm+0QmMCIJ
  alertmanager:
    alertmanager_yaml: AgCGEJilAc3h/WlIOfelHrrFRLWN6NzAOkDprDKdy7i9+GeOqeChqc923Ibyrushob+MsOWtYKthL2KNPYrdsCncdQbe9XOgxonp8XhTCkv6I8ezVs4sUcGCMQHQrbzHOubXc7tpgLz1va8Jz432LY3MRlVa2VkZLSMT1M1gppiTBnhX6Uv63XjpDQDXPmlghxexIzdii6EAgT1KlawygV6k3nfBmfFGw9ReSjUOUZDDFB97i9xjm9JXINhtC9wUFrtYwGubpBT4YaIMTa+9XGMBtvo5ORB//N8TTE0Fq9RgLMqKZmKTSks25+WdrC9F1SmrlD/7TtDPSjWYS1nua21Q2xt1U5MvtjUz49aBTv04s9n2vq20s+5dha32LBmCjuBQ4V0p8TyJQNkW9SXzePl2gZ2XGBDgWwEhiaZaonTX5hfA/2aEHMCPmAu7MAD172fa+r8rU8NPqCrDR7u2S/n70329FImcSjqNFBEttCXQhMw9DJ7BxoXIcSJNwiMThVJUt3qenhKk2st59f+YMosMQIVCN/gkAFttmJz+VhxXEwsMiowMf+XmtmMYDuToJqjeX7hdSH3bH4QDkl188BaPz+00RmmGg4sWMOk7Q9wW6iUMwsAM23ENNmYyvPfJV8i2vjbwx6cNNPnEtj2APKe8uGblQ5zPyJusMJxOZrFe/PSx0r9lUwjJIVsk4+LeGwjp8rCYBgYZEyLgSVwtJObr7pazkYiAM98m/KY4m1c/SPweeXtfFA3qKGrzHRnMHqB8cmIS2Q==
