{{- if .Values.sealedSecret.sshPrivateKey }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-repo
spec:
  encryptedData:
    sshPrivateKey: {{ .Values.sealedSecret.sshPrivateKey }}
    type: {{ .Values.sealedSecret.type }}
    url: {{ .Values.sealedSecret.url }}
  template:
    metadata:
      name: homelab-repo
      namespace: {{ .Release.Namespace }}
      labels:
        argocd.argoproj.io/secret-type: repository
    type: Opaque
{{- end }}
