{{- if .Values.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
spec:
  encryptedData:
    root_user: {{ .Values.sealedSecret.root_user }}
    root_password: {{ .Values.sealedSecret.root_password }}
  template:
    metadata:
      name: minio-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
