image:
  tag: 26.4.0

probes:
  enabled: true

networkPolicy:
  enabled: true

storage:
  size: "1Gi"

backup:
  enabled: true
  schedule: "0 2 * * *"
  s3Endpoint: https://91aa175ac00d47365efeced2071ec4cc.r2.cloudflarestorage.com
  s3Bucket: homelab-backups
  retention:
    daily: 7
    weekly: 4
  sealedSecret:
    aws_access_key_id: AgCl8BkW0n0CXegZVIxfllRNlbvh5CEELQ1RmykfkBEbUpYEhoIFcNRmCn9omrZb1uqsEFChlBZcmEga0MVhZ3cwWTmMSeY8p2qV8ScCEn7WwDGXORmrAvcR8tzypyBjgxE9IjTp7o5YOSQRkCBmyW+AtKNURmze7NkJQZOFYIAQjMTzzT0cYDXwC31TR9g6xqnIIJVMOiXChiA1CjEOCR5wfEiFa2i17r+Bu3D6tMCHvCXJYbtQ/pmhldZ6y61N72w8MGGdTsUPQQltZ9fzlWsj3pdxYFPEKhgJoE7qb/Kd2078KawdfNc90ki3cyo1Pxntzhga7IH0kZ3Lsntyb5pplgTtx8GIH0MXTpiENM2TT2pRBXEXGQepxUG2XQTYRCf+KRZ6FylARdSrduPCHg8QCxuckQ7wkuK7oor9Vw9lv90SsHxIZXy6z0usggZBxS5j/2uyix+mEqFQUkbhr9tvfkP8/n6aYcSv5pPidSoVHRLpEyIB1Ux3DEchUGbFo95NWep57A0ojZM+g3ccsuFSf1zmYPs3jReRMJymbxPe11C1Vbk60zg+CdBNQCPQlrWAxj1FinySs4stTr9S4Tkcj4+qqCVjwpzALhPagy4+ywJuztIHFXCtPekcNTrKFQFa1nChfxkgP61KeIKJR9PApZuwUGowjIaxckQtBqNhoeBCH/HxbaEAmuFYrUDMU4CczPwVw5WkytvK+8pyN7l1Z9tAZk6CL2PXsQ7RkHAWFg==
    aws_secret_access_key: AgCXNVylG5ANjStg1j9Xl5GIrnc5Zo0vv/EkQlLeQtrQ73CjdSlwC8KoU7N8j1477uM569AqrxjzrG4CATBNdq6Cb4PGuu6498J23BRciWINKIyoqBahondPFmRsiHiB4Zo2nHzq8XmZyBOYCpSivFusX+93+mUJ4oEsrBt8gF9AX3qw9N20r0xnZtCH1HeaM8Pt1BF3MSpr9nHMm1UMUpkLlEW5XiZzRi/RxVNObLb2wG66Afqt8KpOLayrp1zQBYst6ZuMW7azfmY1Ulr++yR6hYoRePPjglMiV9QZaJIovOM8GDLScYI043j4OcZj9n3RIOLcmb/hSBWaLMLMTXMZGnwa5Zqs72qHXZFuV8x41BMdfEvuyEoXovDx2s0PErhD4JMddSUsGjO2j7eYHbYkVzh3fAhFasUPEsSFBIe+RcPZCRhM9d1C1EXhdTWc9jqdV8Tmd5W1oY20vkDfVp295ZD/n8pIrjLxHvKZRH4foH0DXsTU1M4uYwUQ3hppLf1axZ4IBewq3xBqbopNNnwsrowvnHYmZkM9D7gYLWrU0A2iXKhC+Q6kbN9Gfp4tI/Fy/wLj9YS4mqh5Rc+6Rvlko+J98z5g5wsAQJn2uAwwosdY5VB5Eoz6ZLKMrML+DZmVlPm9xoq/8aGUvwGP/3C8RzaeTkAtRQ/SrUheCk91za57S7Ak3/9I1a6Kj3akngBztgyRl+GED+VMp0xDLB7lkMxB6qbW3VtNRcg2r58RlGpSv3czC8yvXl7/uGqTbl0ytyyAcI5OE2a+ptl6Y9Xp
    restic_password: AgB93KP5t2AczsfriaTgttY6NCASV/Yw7UDcEUTpxPINqLurAebLbcSD/INWClVyPBSuxtU+dS372lSNAH4zegsnzeN81xx1KKu3DEpXz0ONRy7tGInmgtsDUwhycEa6c3gngZbiCtjZZuu3jo+8PFUaTRkLODIANqQB0VmdUBkqSoNNlxdS8cZbelxHoIKRYnowJZJbw/JmJgUBYs79cRaN5lQWn7EU3mSRMSQfMpEycyA2xLDzUwuUVHd26Y2tpAj9TrrVkElBPkEN6ZWK730lBOsFUWbEhEpxMqt4+lT049K5c7ca9KSAneBE0u2wAAhKPDMlKZUUeQd3/PdryZb/rQL5LX+KPTqsiOdStAFNsV30db/ny8tpeb/ZR4dLrE6Ulh94rcKU4uDily59t0oe7X5NQmJYMT8KDbOaXGeHlgX8LaX6IQOLK4/Iai1im3UzODtrs38XOEzBG9jTO5PuqgdpzSpI3GdPAC7ENgcWXw+TMcjjzyAVVZd/N8Rl8cbMHKaP6VceKDb8VVKi0nUDVnT8pVMiG6VCMqv3yd2Eh04zV5xVyCnKZTJxQ5tk2mkWcwbxKPVLSPe74mHrMhHPdqCaQujkNrXyBo94dMz+1v6ZlFhMNMvN8qD9faNLB6WMMZnOIt+Q9Mj6cSWbI0bnrVeNRihlxgaWpoQpYpn5vgyaJTvngHtfAIoFDTEYPu4wu2i9o2bH3uYby9d4fHAtR6YgWtY2ZM46FxU8WDkejWjdfD7pyE3RbnhYdw==
