image:
  tag: 26.4.0

probes:
  enabled: true

networkPolicy:
  enabled: true

storage:
  size: "500Mi"

backup:
  enabled: true
  schedule: "0 2 * * *"
  s3Endpoint: https://91aa175ac00d47365efeced2071ec4cc.r2.cloudflarestorage.com
  s3Bucket: homelab-backups-staging
  retention:
    daily: 7
    weekly: 4
  sealedSecret:
    aws_access_key_id: AgAlegmvZn2Tj1l/dOoWN/qmOgjoygJw/n8bTWtHhRn1ZzrSkW+OSD7Kg2k4BETVS0w8EaDjKvaRu9iNqwv7wBi7plNL6TVProigCziP/xe5DvydgmD1fi6tGkIQMb7gtvaBWI8nPTJlB9glbTPQI16Zm99Qw5sSG+MQFmPNKiM3gAonGkd5S6vwJwnN8uTjF6QEA/Pqj5gBAhcO2flJ6J7+vJuWGuHFyVqrESA8blpvVzragQpanpJKHj8IsEDO0fmthz1l4E+7h9YbFcLkmwiF7ukUtsXzAEGouOmKVEjlIGOmLRTznewxft5buAXnfJsA74uXQwB6c9m/ubiCBgqDygNBLMwPEYqxqGVsr0C0Vh2O1bgpcn10J5OZ1sYf8uOZ73dIw85/EgRRZLR9xLww11yb09eOC1ftRo6cOz2VmJAnguOlIe2hqUXj+ljD+7oGhr8duhtJR78ENwHQYyahndN7DKYpxPArqnNlVyYuat4vf85EnaXHj0DJ02D0uqWFe4yItCr4o8kBau2Bn5/YOixonFg65X4GFefeXaz7aSdUgAlwSXyxsq7AaWQo3Qo15ymMdweHghRbEM/GeGKjjdcnhlqC8O3DmpCewQ8Ak+F/DxfCnTuCezD0CKnWYZ8OZYzqF6xOp6mecyXutX0ufmW7fzNz2WEL0JTkVDq67bYXqRYt9Tn3YAmvtucFSnXXopfy7PVvQ3Q52W6XILLCPXUS+GtYz/JGNrhNVD2hsg==
    aws_secret_access_key: AgC+X8ufO7Pw8h5eULc25o63/R43uAXicL/LvvXenQCjJxUJW9uitKOHdShVnNyTvHIcf4YfvgiOAmdabyREE8A5BR8IKBLDiyRfJT4253iieGp3rY7Di7o5kr2OPsNWsdgc5JbkNDC4VCRY0UQAI9DrqsMNja/XmOsQAuRNZk5l14mIjNu4nXODt02bsrDfpO5IT4c8amM7VAot8zpYTekQ/SgBYeTcjNtV37GFebKRJmrkJuu9FbZIbMH67RF5b8PTnD5w++nXAdHkR58j1zsyE6PwbGLUT0bB7+vaijIsxgQC/W2QySPLYI7SXe3EqRSAQBoDpj/OZzu6Sp6PzpYONK+VhqZYS4m+tlLDwX8g+4Vq69mRTx8L7bJIVrCQ1g9xRix8O8JWcbcreIohZC7Kadqf+DAbvFQuIj4WLO19G8yrjeR+HzX4MZwwO/zh9JUM76btuRNvHkx9BpUDoqHpBKorDdkYloHPp0WZItJaFICzkL7lQnID8rLVAMVkPpI6JxWSe+VEfgYpr0O0Ikm4j4fJH1UTtsCPfEUzfKYRovT3zlWgBeT+VRxVrqW+94430BuF5hifgivO83FgMSpwmT7qQr8mDiUMEvOp9+s+Qkzo/jxUc4j2HhpLiOhH+trmZxv1xC49bpDV49UTHH7tfw+/gRzbyN5KbQd49CwU2g4Jp6FYv3ZIIOLQQqwXRhbuQJ+L3XEjmIV1ZgDE5nVpWse1Ide78ox21p1ONAs9OwlzSTOdelvtAQ1kOgbsw3Q5Mr9rEZh3qrD359bHgbN/
    restic_password: AgCKcqLcJltCAfYnQKwdzOOFCpheAbK/xy0vArFqiMGgjpYGgRaFjDHZ53c3ieLkHWEy6B8Dl3bJ6F+y62vbI1O91ZbHLTJv7WyWRPCY0wP2qFb3NRipT1zSIrMRnl2EO/qLP2vuE8fF5WvjaS+JKgO3pPSrqGHnjNnr9Da0AVnAv9+1KVG0IQVQF6sNf/gh/yi43yuomCSPC7ujv+rpdJsNn4atYfN2wvFigUAE93LjjOYy4JU9ofLTK/43ZPvhqPHdqrTcyZyzk1SX6JZCqFDJivBiALRfWciUlgxRPYWW8itbw+yuXFJ/N3BrIvP/cXZN4gf7MJfu4i0CI0usQEhns9NfiSZgDyyQwFOXTALGhkLU98Jiv2+7f0tfL++AcJ0r5uFAUvy0U20vADPhn4ryEoaWlhmmxD2V2M0exAP5YVHDxC/KFPPNR2cRfHJO5B4gxY/qUM/y5v1WURdLwUf42SIt/U2G+sEe5MirqbbdAl3wMCIdz/d/P94XDV4NicxxDbdW7ik31dLjqoCbHiV+4NlsZ+KE01LgwlxuPprdL4RN2QMQWzA0WWv7Q4v+sYmZuu9ZXArq+lAx5h/lomnF2PXqjY1sPZgALCsEtRd4+Hz2G7ZR+apdNkNRCNfNVhtiYACNGxOvYlumR/wHmX70obqJPnQoyczZsLZRkuS2lx2zZKu8kUxv8T0PWtXdyYyozxsLgYL6nGlUGC0XVWDOHkE4j3vRx7q8iGvl8SwxfZUAVqsHPwJxPycBEw==
