image:
  repository: ghcr.io/nopsqi/astro
  tag: sha-179dac7a94978019e783cbdb68fdc4602e538d60

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "0.5"
    memory: "256Mi"

storage:
  size: "1Gi"
