image:
  repository: ghcr.io/nopsqi/astro
  tag: sha-526256bad11016e5c9d3cb2c8cfe22c895713400

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "0.5"
    memory: "256Mi"

storage:
  size: "1Gi"
