apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naila-pvc
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
