{{- if .Values.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: naila-secret
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.sealedSecret.DATABASE_URL }}
    APP_SECRET: {{ .Values.sealedSecret.APP_SECRET }}
    POSTGRES_USER: {{ .Values.sealedSecret.POSTGRES_USER }}
    POSTGRES_PASSWORD: {{ .Values.sealedSecret.POSTGRES_PASSWORD }}
    POSTGRES_DB: {{ .Values.sealedSecret.POSTGRES_DB }}
    OPENROUTER_API_KEY: {{ .Values.sealedSecret.OPENROUTER_API_KEY }}
    {{- with .Values.sealedSecret.ANTHROPIC_API_KEY }}
    ANTHROPIC_API_KEY: {{ . }}
    {{- end }}
    {{- with .Values.sealedSecret.OPENAI_API_KEY }}
    OPENAI_API_KEY: {{ . }}
    {{- end }}
    {{- with .Values.sealedSecret.GOOGLE_GENERATIVE_AI_API_KEY }}
    GOOGLE_GENERATIVE_AI_API_KEY: {{ . }}
    {{- end }}
    {{- with .Values.sealedSecret.ADMIN_EMAIL }}
    ADMIN_EMAIL: {{ . }}
    {{- end }}
    {{- with .Values.sealedSecret.ADMIN_PASSWORD }}
    ADMIN_PASSWORD: {{ . }}
    {{- end }}
  template:
    metadata:
      name: naila-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.sealedSecret.dockerconfigjson }}
  template:
    metadata:
      name: ghcr-pull
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
