{{- if .Values.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: naila-secret
spec:
  encryptedData:
    NAILA_DISCORD_TOKEN: {{ .Values.sealedSecret.discord_token }}
    NAILA_DISCORD_CLIENT_SECRET: {{ .Values.sealedSecret.discord_client_secret }}
    NAILA_SECRET_KEY: {{ .Values.sealedSecret.secret_key }}
    {{- with .Values.sealedSecret.anthropic_api_key }}
    ANTHROPIC_API_KEY: {{ . }}
    {{- end }}
    {{- with .Values.sealedSecret.gemini_api_key }}
    GEMINI_API_KEY: {{ . }}
    {{- end }}
    {{- with .Values.sealedSecret.openai_api_key }}
    OPENAI_API_KEY: {{ . }}
    {{- end }}
  template:
    metadata:
      name: naila-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.sealedSecret.dockerconfigjson }}
  template:
    metadata:
      name: ghcr-pull
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
