{{- if .Values.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: naila-secret
spec:
  encryptedData:
    DISCORD_TOKEN: {{ .Values.sealedSecret.discord_token }}
    ANTHROPIC_API_KEY: {{ .Values.sealedSecret.anthropic_api_key }}
    GEMINI_API_KEY: {{ .Values.sealedSecret.gemini_api_key }}
  template:
    metadata:
      name: naila-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.sealedSecret.dockerconfigjson }}
  template:
    metadata:
      name: ghcr-pull
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
