{{- if .Values.sealedSecrets.grafana }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
spec:
  encryptedData:
    admin-user: {{ index .Values.sealedSecrets.grafana "admin_user" }}
    admin-password: {{ index .Values.sealedSecrets.grafana "admin_password" }}
  template:
    metadata:
      name: grafana-admin-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
