{{- if .Values.sealedSecrets.alertmanager }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
spec:
  encryptedData:
    alertmanager.yaml: {{ index .Values.sealedSecrets.alertmanager "alertmanager_yaml" }}
  template:
    metadata:
      name: alertmanager-discord
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
