- name: update hetzner server
  hosts: hetzner
  remote_user: root

  tasks:
  - name: update apt cache
    ansible.builtin.apt:
      update_cache: yes
  - name: upgrade packages
    ansible.builtin.apt:
      upgrade: dist


- name: configure hetzner server
  hosts: hetzner
  remote_user: root

  tasks:
  - name: install tailscale
    ansible.builtin.shell: curl -fsSL https://tailscale.com/install.sh | sh
    args:
      creates: /usr/bin/tailscale
  - name: get hetzner tailscale ipv4
    ansible.builtin.shell: tailscale ip -4
    register: tailscale_ipv4
  - name: create k3s config
    ansible.builtin.copy:
      content: |
        tls-san:
          - {{ tailscale_ipv4.stdout }}
      dest: /etc/rancher/k3s/config.yaml
  - name: install k3s
    ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
    args:
      creates: /usr/local/bin/k3s

- name: install and apply argocd manifest
  hosts: hetzner
  remote_user: root

  tasks:
  - name: install argocd
    ansible.builtin.shell: kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
  - name: apply argocd manifest
    ansible.builtin.shell: kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
