image:
  tag: RELEASE.2025-09-07T16-13-09Z

probes:
  enabled: true

networkPolicy:
  enabled: true

storage:
  size: "500Mi"

sealedSecret:
  root_user: AgDALF9eSBq7r58UeM93g3ZTbJUMqpbUjnAHTMcjijp21e4HmWSeFgmOOEdKEuG6Z2H8WUSsc2iDDnj3DK8LIBm0pFjgeH5jgeLKFTJwxx9HmLmuxdzQrKBAbMssHRSZrh7vhNt4lIJa44+gkzxNjSkoz9UbazPZGZtM2HiKnRTXodqfe4/SkKWC648qeDoLoYJo4VnThyHYE27F7McpIAGI+VskncEtu/3a9+O6YeSBGMMedZJDF68Vmb4bdsLLH9O8UjipdxJQ4KWmf86RduL3729SUoW16YMbcSs8GKGa24Y36LPaM8pQCPxt5ji1uDnOj7EiQk71apzoxDsw5IHN7aFi7Yj2rgyfTAMDN8ltiaWN/RFoc+PTYqi0GGLhlXcuIDGsGNsUuSDW3GcMMJxnYIGv4NOqr+3Gb66/SY+kxTOQfgqdKltzbRNs7PeoH+vBIiMBcR0ccbCWNUxbdwJqQsZW7K7IA2oNFZUhssSjfxhSjKp6svDh3uY26pkwQfM/HktGQs1oXceposP1XtJahJcK84fwYR7WufPCXbNN/I44JZr7qG/2daybh21bycKBtutyeZP0sBEk+LSXhlFGM46V6PyYo9L1zdnBtWnXkpGVy70NONSAYdEf6RnNLz/v82PFEep5nd29q1IwjSziIKVtTANZEtzzQqzn1WKRl40NHL4d3Nue/WdzoxwZTNNJhcBqw/1u+OCoi4VQ
  root_password: AgArZIjPB7RvBw6J+6T6paltJO4NZ2VV1SLej0p57/E3CUZqTTIMFbBA1L3jnhcX3zsnt+wAEMmLl1NdUTCYVbk6auTRNzThfuL9wG45HncuK/X3AnKsf9IB6hYXl0QOfcfSf+G1QJgipe0ABawGKzIjQ97yqoyAiBAi3g5G6IaJQBQq8XDoCtj4RVQYJ/CCLPxIKty1sUamkEMofXiU1OkdiOsvCX2RbiurIFcUkB0vyshG1CKcRV8v23Ir7ik8Klv4b9ra5xU3s9vkpW8UR+gF8HXdtq0s1PbtZdQFqVWikk7pKeTZ0tuN34PcEVo6/gL2pI1Y8PlTK4PmkrwcgAGl2dsHu2+cFn37J3lRAszps2J/v5VarWcGKPo0kcpsMpgzQ7napf99TWxj70fGVpGphPK5KF6JjRK6nhdTQvPrYa4/6qK9KzxMHKxdPRimQ7RfwIelF9hG4ywj6pQ4ymTK7DUKGokbHQ4cX9Ru2bExjRb95KGpmLOf8GIi+2pncDKgEgtQoPL3EH0bc3FQL6dmUd+7hcaFH4zirdzC8XuiJjz0AaucjwE6hR5kF8VqQEclU553UIlyx3UpUWjLWvBHl0FHHW777OEalkWM/H36DurmLG6GpwXLDnPR2g7yl7cjBL3qgo/TEXQDNmQcEedYlmpX+nBR1VfhS925HKUhjrFCBvdd62jZEPXwB1jU2olVTVXPzZKxV/xgmscOBD6x
